### ISSUE TITLE
Crashes when click Push notification and opening Chucker

### ISSUE THREAD

**Issue by devoma** [ChuckerTeam/chucker#1009]
Crashes when click Push notification and opening Chucker

    debugImplementation "com.github.chuckerteam.chucker:library:3.5.2"
    releaseImplementation "com.github.chuckerteam.chucker:library-no-op:3.5.2"

Stack trace: 

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.debug/com.chuckerteam.chucker.internal.ui.MainActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f040171 a=10}, theme={InheritanceMap=[id=0x7f1402fecom.myapp.debug:style/ThemeOverlay.MaterialComponents.Dark.ActionBar, id=0x7f1402adcom.myapp.debug:style/ThemeOverlay.AppCompat.Dark.ActionBar, id=0x7f140077com.myapp.debug:style/Base.ThemeOverlay.AppCompat.Dark.ActionBar, id=0x7f140076com.myapp.debug:style/Base.ThemeOverlay.AppCompat.Dark, id=0x7f140177com.myapp.debug:style/Platform.ThemeOverlay.AppCompat.Dark, id=0x7f140176com.myapp.debug:style/Platform.ThemeOverlay.AppCompat], Themes=[com.myapp.debug:style/ThemeOverlay.MaterialComponents.Dark.ActionBar, forced, com.myapp.debug:style/Chucker.Theme, forced, com.myapp.debug:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}

## :iphone: Tech info
Device: All devices
   
    compileSdkVersion 33
    minSdkVersion 24
    targetSdkVersion 33`
    
    
    compileOptions {
         sourceCompatibility JavaVersion.VERSION_1_8
         targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
         jvmTarget = '1.8'
    }

    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "com.google.android.material:material:1.8.0"
    implementation 'androidx.core:core-ktx:1.10.0'
    implementation 'androidx.activity:activity-ktx:1.7.1'
    implementation 'androidx.fragment:fragment-ktx:1.5.7'

**Comment by cortinico** [comment]
> compileSdkVersion 33

As you're on 33, could you try the version from the SNAPSHOT as suggested here:
https://github.com/ChuckerTeam/chucker#snapshots-
And please say if the bug is already fixed?

**Comment by cortinico** [comment]
> But I get errror:

Sadly you need to be on AGP 8.0.0 and on Java 17 to try the latest SNAPSHOTS.

**Comment by devoma** [comment]
@cortinico 
figured out the crash happens here
![image](https://user-images.githubusercontent.com/66753065/233995089-2a36caf3-8765-4cd6-93b2-2e3eb95ea586.png)

**Comment by cortinico** [comment]
> figured out the crash happens here

Is the crash happening also on the latest SNAPSHOT?
Please note that you need Java 17, not 15

**Comment by devoma** [comment]
I used
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    
    Gradle Version: 8.1.1.
    AGP: 7.4.2
    
But still get crash:

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.debug/com.chuckerteam.chucker.internal.ui.MainActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f040171 a=7}, theme={InheritanceMap=[id=0x7f1402facom.myapp.debug:style/ThemeOverlay.MaterialComponents.Dark.ActionBar, id=0x7f1402a9com.myapp.debug:style/ThemeOverlay.AppCompat.Dark.ActionBar, id=0x7f140077com.myapp.debug:style/Base.ThemeOverlay.AppCompat.Dark.ActionBar, id=0x7f140076com.myapp.debug:style/Base.ThemeOverlay.AppCompat.Dark, id=0x7f140178com.myapp.debug:style/Platform.ThemeOverlay.AppCompat.Dark, id=0x7f140177com.myapp.debug:style/Platform.ThemeOverlay.AppCompat], Themes=[com.myapp.debug:style/ThemeOverlay.MaterialComponents.Dark.ActionBar, forced, com.myapp.debug:style/Chucker.Theme, forced, com.myapp.debug:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}

**Comment by cortinico** [comment]
> @cortinico
> I used
> debugImplementation "com.github.chuckerteam.chucker:library:4.0.0-SNAPSHOT"
> releaseImplementation "com.github.chuckerteam.chucker:library-no-op:4.0.0-SNAPSHOT"

I tried to reproduce, but I'm not able, sadly.
Could you create a reproducer project where this crash happens consistently?

**Comment by kanch231004** [comment]
Will we not be able to use Chucker on Android 13, if not migrating project to Java 17 and hence unable to use snapshot 4.0.0 version?
Is there any alternative for Android 13?

**Comment by kanch231004** [comment]
Can you please update on the above?

**Comment by cortinico** [comment]
> Will we not be able to use Chucker on Android 13, if not migrating project to Java 17 and hence unable to use snapshot 4.0.0 version?
> Is there any alternative for Android 13?

You can use the SNAPSHOT even with Java 11, you don't need to upgrade AGP.
Version 4.0.0 will aslo be out in the next days/weeks so that should solve your issue.

**Comment by devoma** [comment]
I solved the problem. 
I removed those lines from the chucker code that led to the crash, everything worked. 
then I realized, or it seems to me that it crashed because my project had similar layouts, but I'm not sure

**Comment by cortinico** [comment]
> I solved the problem.

Closing because of this
